[package]
name = "eco-paste"
version = "0.0.5"
description = "一款开源的跨平台剪切板管理工具"
authors = []
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
tauri = { version = "1", features = [ "window-set-title", "dialog-open", "dialog-ask", "process-relaunch", "updater", "shell-sidecar", "window-center", "window-set-position", "window-start-dragging", "path-all", "os-all", "shell-open", "protocol-asset", "global-shortcut-all", "fs-all", "system-tray", "macos-private-api"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-theme = "0.2.0"
tauri-plugin-single-instance = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
tauri-plugin-autostart = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
tauri-plugin-sql = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1",features = ["sqlite"] }
window-shadows = "0.2.2"
clipboard-rs = "0.1.11"
tauri-plugin-context-menu = { git = "https://github.com/c2r0b/tauri-plugin-context-menu", branch = "main" }
mouse_position = "0.1.4"
flate2 = "1.0.30"
tar = "0.4.41"
current_locale = "0.1.1"
rdev = "0.5.3"

[target."cfg(target_os = \"macos\")".dependencies]
cocoa = "0.25.0"
objc = "0.2.7"

[target."cfg(target_os = \"windows\")".dependencies]
winapi = { version = "0.3", features = ["winuser"] }

[target."cfg(target_os = \"linux\")".dependencies]
showfile = "0.1.1"

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
devtools = ["tauri/devtools"]
