[package]
name = "eco-paste"
version = "0.2.0-beta.2"
description = "一款开源的跨平台剪贴板管理工具"
authors = []
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1", features = [] }
build-info-build = "0.0.38"

[dependencies]
tauri = { version = "1", features = [ "window-set-skip-taskbar", "cli", "window-set-title", "dialog-open", "dialog-ask", "process-relaunch", "updater", "shell-sidecar", "window-center", "window-set-position", "window-start-dragging", "path-all", "os-all", "shell-open", "protocol-asset", "global-shortcut-all", "fs-all", "system-tray", "macos-private-api"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-theme = "1.0.0"
tauri-plugin-single-instance = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
tauri-plugin-autostart = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
tauri-plugin-sql = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1",features = ["sqlite"] }
tauri-plugin-log = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
window-shadows = "0.2.2"
clipboard-rs = "0.2.1"
tauri-plugin-context-menu = { git = "https://github.com/c2r0b/tauri-plugin-context-menu", branch = "main" }
mouse_position = "0.1.4"
flate2 = "1.0.30"
tar = "0.4.41"
current_locale = "0.1.1"
window-vibrancy = "0.4.3"
sys-info = "0.9.1"
log = "0.4.22"
tauri-plugin-window-state = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
build-info = "0.0.38"
fs_extra = "1.3.0"

[patch.crates-io]
tao = { git = "https://github.com/EcoPasteHub/tao", branch = "v0.16" }
tauri = { git = "https://github.com/EcoPasteHub/tauri", branch = "1.x" }

[target."cfg(target_os = \"macos\")".dependencies]
cocoa = "0.25.0"
objc = "0.2.7"
macos-accessibility-client = "0.0.1"

[target."cfg(target_os = \"windows\")".dependencies]
winapi = { version = "0.3", features = ["winuser", "windef"] }
enigo = "0.2.1"

[target."cfg(target_os = \"linux\")".dependencies]
showfile = "0.1.1"
x11 = "2.21.0"
rdev = "0.5.3"
reqwest = { version = "0.11.27", features = ["native-tls-vendored"] }

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
devtools = ["tauri/devtools"]
